// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4N1QDKnNgG2NpJnkAZtkqud_7WL0ONsc',
    appId: '1:987744605674:ios:831f8f7d3ae4070b04ce93',
    messagingSenderId: '987744605674',
    projectId: 'tele-health-3b847',
    databaseURL: 'https://tele-health-3b847-default-rtdb.firebaseio.com',
    storageBucket: 'tele-health-3b847.appspot.com',
    iosBundleId: 'com.safelify.org',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgW9uH8bdR2-VZWlYwPFhIiUSHDdjqkyY',
    appId: '1:987744605674:android:974d34dcbac59c2904ce93',
    messagingSenderId: '987744605674',
    projectId: 'tele-health-3b847',
    databaseURL: 'https://tele-health-3b847-default-rtdb.firebaseio.com',
    storageBucket: 'tele-health-3b847.appspot.com',
  );

}